# Generated by Django 5.1.2 on 2025-04-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Project Manager', 'Project Manager'), ('Site Engineer', 'Site Engineer'), ('Croxx', 'Croxx'), ('Stronger', 'Stronger'), ('ROW Coordinator', 'ROW Coordinator'), ('Quality Inspector', 'Quality Inspector'), ('User', 'User'), ('Viewer', 'Viewer')], max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('subtasks', models.TextField()),
                ('milestone', models.CharField(choices=[('select Milestone', 'select Milestone'), ('Desktop Survey Design', 'Desktop Survey Design'), ('Design/Network Health Checkup', 'Design/Network Health Checkup'), ('HOTO-Existing', 'HOTO-Existing'), ('Detailed Design', 'Detailed Design'), ('ROW(Right of way)', 'ROW(Right of way)'), ('IFC(Issued For Construction)', 'IFC(Issued For Construction)'), ('IC(Initial Construction)', 'IC(Initial Construction)'), ('As-Built', 'As-Built'), ('HOTO(Final)', 'HOTO(Final)')], max_length=255)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('TS', 'Telangana'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('GJ', 'Gujarat'), ('WB', 'West Bengal'), ('UP', 'Uttar Pradesh')], max_length=50)),
                ('business_area', models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Operations', 'Operations')], max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending', max_length=50)),
                ('assign_to', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.user')),
            ],
        ),
    ]
