# Generated by Django 5.1.2 on 2025-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_task_end_date_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='block',
            field=models.CharField(choices=[('Block1', 'Block1'), ('Block2', 'Block2'), ('Block3', 'Block3'), ('Block4', 'Block4'), ('Block5', 'Block5')], max_length=50),
        ),
    ]
